### ISSUE TITLE
Left door starts open and cannot be closed

### ISSUE THREAD

**Issue by jayeye2011** [krzysk1/tomahawk#3]
Aerofly FS 2 Steam Edition (current version 2.0.6)
Regardless of start location (ready to taxi or ready to take off) the Tomahawk always starts with the Left door in the open position. There is no activation point on the door latch so it is impossible to close (or later open) the door. The right door starts closed but it also does not have a mouse activation point defined for its door latch. Obviously it is not ideal to take off in this situation although  Aerofly FS2 does not model damage and there is no crash & burn implemented either. I know you have not released this addon but     could you just fix it so the door is always closed at least so it's flyable.

**Comment by jayeye2011** [comment]
Left door also starts open state in Aerofly FS 4. 
![20221202053229_1](https://user-images.githubusercontent.com/69315126/205304626-38b8c9d0-0a36-4963-a499-5b970756983c.jpg)

![20221202053223_1](https://user-images.githubusercontent.com/69315126/205304697-9b6bd299-8fdd-46c0-8050-9e22931d996b.jpg)

**Comment by jayeye2011** [comment]
Okay, looking at the tomahawk.tmd file, I see that you have some kind of oddball setup so that the left door automatically closes when the airplane is moving, but opens when the airplane is stopped. 
// door
            <[servolinear][ServoDoor][]
                <[string8][Input][AirspeedIndicator.IndicatedAirspeed]>
                <[float64][OutputSpeed][0.5]>
                <[float64][Position][0.0]>
                <[float64array][InputPosition][ 1.0 2.0 ]>
                <[float64array][OutputPosition][ 1.0 0.0 ]>
            >
This is pretty annoying during taxi from ramp as every time you stop the door opens by itself.  I suggest, since you do not have any door latch manipulators programmed that you just keep the door shut all the time as default.

**Comment by jayeye2011** [comment]
Well, since this automatic door control is intentional I guess its not a bug so I will go ahead and close my issue.

**Comment by jayeye2011** [comment]
Well, since this automatic door control is intentional I guess its not a bug so I will go ahead and close my issue.

**Comment by krzysk1** [comment]
thanks for remarks. I will add door handle control  as well as other controls

**Comment by jayeye2011** [comment]
Just keep the door closed all the time by changing
            <[servolinear][ServoDoor][]
                <[string8][Input][AirspeedIndicator.IndicatedAirspeed]>
                <[float64][OutputSpeed][0.5]>
                <[float64][Position][0.0]>
                <[float64array][InputPosition][ 1.0 2.0 ]>
                <[float64array][OutputPosition][ 1.0 0.0 ]>
            >
TO
            <[servolinear][ServoDoor][]
                <[string8][Input][AirspeedIndicator.IndicatedAirspeed]>
                <[float64][OutputSpeed][0.5]>
                <[float64][Position][0.0]>
                <[float64array][InputPosition][ 1.0 2.0 ]>
                <[float64array][OutputPosition][ 0.0 0.0 ]>  // just keep the door closed all the time
            >

**Comment by krzysk1** [comment]
I used you proposal till adding door handle control
