### ISSUE TITLE
Gyro Compass 180 deg off

### ISSUE THREAD

**Issue by jayeye2011** [krzysk1/tomahawk#5]
Mag compass indicates South
Gyro Compass indicates North
![20230101114928_1](https://user-images.githubusercontent.com/69315126/210183069-30916669-325a-4147-8263-42ac0c8f7c72.jpg)

**Comment by krzysk1** [comment]
Gyro Compass  will be fixed

**Comment by jayeye2011** [comment]
Thanks.

**Comment by krzysk1** [comment]
fixed
