### ISSUE TITLE
Vertical Stabilizer Non-Zero Incidence Angle Causes Neutral Rudder Constant Sideslip 

### ISSUE THREAD

**Issue by jayeye2011** [krzysk1/tomahawk#8]
Constant Sideslip with rudder centered as shown
![constant sideslip](https://user-images.githubusercontent.com/69315126/218733633-546ff4e2-a91f-4535-b4d9-38e8bdb77979.jpg)

This is caused by non-zero vertical stabilizer incidence angle.
            <[aerowing][VertStabilizerAero][]
                <[string8][Body][Fuselage]>
                <[string8][Flap0Control][ServoRudder.Output]>
                <[float64array][StationY]           [ 0.0 0.0 ]>
                <[float64array][StationLE]          [ -4.42690 -3.31020 ]>
                <[float64array][StationTE]          [ -5.24986 -4.89516 ]>
                <[float64array][StationZ]           [ 1.54146 0.0 ]>
                <[float64array][StationIncidence]   [ 0.03491 0.01745 ]>  // ???? constant side slip WTF? FOOBAR - SHOULD BE ZERO
                <[uint32array][StationFlap]         [ 1 0 ]>
                <[float64array][StationFlapFraction][ 0.28 0.00 ]>
                <[float64][AspectRatioMultiplier][1.0]>
                <[string8][AirfoilRoot][AirfoilVerticalStabilizer]>
                <[string8][AirfoilTip][AirfoilVerticalStabilizer]>
                <[float64][GroundEffectFactor][1.0]>
                <[float64][GroundEffectScale][1.0]>
            >

IF the intent was to have propwash effects, then the correct implementation would be to define the PropWash parameters in the aerowing objects of the wings, horizontal stabs, and vertical stabilizer.

**Comment by krzysk1** [comment]
that's right, thanks. fixed
