### ISSUE TITLE
USEFUL DATA ON PA-38-112 TOMAHAWK II

### ISSUE THREAD

**Issue by jayeye2011** [krzysk1/tomahawk#9]
The current tomahawk.tmd file does not yield performance characteristics of aircraft specifications and needs further adjustment.
Airfoil, wing and stabilizer incidence angles need inspection and correction to generate more realistic flight performance envelope.
This gives info on wing dihedral and incidence angles
source: https://www.aerospacefacts.com/plane/aircraft.php?plane_id=131
[WWW.AEROSPACEFACTS.COM - aircraft details.pdf](https://github.com/krzysk1/tomahawk/files/10732325/WWW.AEROSPACEFACTS.COM.-.aircraft.details.pdf)
http://www.pilotfriend.com/aircraft%20performance/Piper/15.htm
https://www.pilotmall.com/blogs/news/piper-tomahawk-pa-38-everything-you-need-to-know
https://www.aviationconsumer.com/aircraftreviews/piper-pa-38-tomahawk/
https://www.flyingmag.com/the-piper-tomahawk-a-lot-more-airplane-for-a-lot-less-money/
http://snapflight.com/PA38-112_files/Piper%20PA-38-112%20POH.pdf

**Comment by jayeye2011** [comment]
Here is my attempt to get the tomahawk to fly at a reasonable normal cruise speed with close to 0 pitch attitude using 2.0 degree wing incidence. But this required the use of -0.5 degree incidence on the horizontal stabilizers to try to get 0 pitch attitude. This setup resulted in an 80 knot cruise speed with 0 elevator trim. However this is somewhat realistic as the real tomahawk require
![20230214055638_1](https://user-images.githubusercontent.com/69315126/218760946-86048442-2714-44b7-8bb8-285be42f5b63.jpg)
Here is the tmd file that was used.

d down elevator trim to fly at 100 knots from what I understand. The RPM seems a just a little bit low for cruise speed but this ain't X-Plane 11 so good enough.
[20230214 2deg wings tomahawk_tmd.zip](https://github.com/krzysk1/tomahawk/files/10733105/20230214.2deg.wings.tomahawk_tmd.zip)

**Comment by krzysk1** [comment]
Thanks for update. I used it
Done
